from pygments import lexers

VERSION = "1.0.2"

LANGUAGES = {
    'txt': lexers.TodotxtLexer,
    'py': 'python', 'py3': 'python', 'pyw': 'python', 'pyi': 'python',
    'bash': lexers.BashLexer, 'bashrc': lexers.BashLexer, 'sh': lexers.BashLexer, 'ksh': lexers.BashLexer,
    'lua': 'lua', 'wlua': 'lua',
    'luau': lexers.LuauLexer,
    'java': 'java', 'js': 'javascript', 'jsm': 'javascript', 'mjs': 'javascript', 'cjs': 'javascript',
    'c': 'c', 'h': 'c', 'idc': 'c',
    'cs': lexers.CSharpLexer, 'csx': lexers.CSharpLexer,
    'go': lexers.GoLexer,
    'kt': lexers.KotlinLexer, 'kts': lexers.KotlinLexer,
    'php': lexers.PhpLexer,
    'mojo': lexers.MojoLexer, '🔥': lexers.MojoLexer,
    'as': lexers.ActionScript3Lexer,
    'cpp': 'c++', 'hpp': 'c++', 'c++': 'c++', 'h++': 'c++',
    'css': 'css',
    'html': 'html', 'htm': 'html', 'xhtml': 'html',
    'cljs': lexers.ClojureScriptLexer,
    'cyp': lexers.CypherLexer, 'cypher': lexers.CypherLexer,
    'cu': lexers.CudaLexer, 'cuh': lexers.CudaLexer,
    'flo': lexers.FloScriptLexer,
    'sql': lexers.SqlLexer, 'ddl': lexers.SqlLexer, 'dml': lexers.SqlLexer,
    'm': lexers.MatlabLexer, 'matlab': lexers.MatlabLexer,
    'gcode': lexers.GcodeLexer,
    'pyx': lexers.CythonLexer, 'pxd': lexers.CythonLexer, 'pxi': lexers.CythonLexer,
    'bf': lexers.BrainfuckLexer, 'b': lexers.BrainfuckLexer,
    'applescript': lexers.AppleScriptLexer,
    'ino': lexers.ArduinoLexer,
    'cr': lexers.CrystalLexer,
    'coffee': lexers.CoffeeScriptLexer,
    'pas': lexers.DelphiLexer, 'dpr': lexers.DelphiLexer,
    'swift': lexers.SwiftLexer,
    'pl': lexers.PerlLexer, 'pc': lexers.perl.PerlLexer,
    'bat': lexers.BatchLexer, 'cmd': lexers.BatchLexer,
    'json': 'json', 'jsonl': 'json', 'ndjson': 'json', 'jsonld': lexers.JsonLdLexer,
    'rs': 'rust',
    'rb': 'ruby', 'rbi': 'ruby', 'rbw': 'ruby', 'rake': 'ruby',
    'ts': 'typescript',
    'xml': 'xml',
    'ps1': lexers.PowerShellLexer, 'psm1': lexers.PowerShellLexer,
    'moon': lexers.MoonScriptLexer,
    'ms': lexers.MiniScriptLexer,
    'sh-session': lexers.BashSessionLexer, 'shell-session': lexers.BashSessionLexer,
    'dylan': lexers.DylanLexer, 'dyl': lexers.DylanLexer,
    'dylan-console': lexers.DylanConsoleLexer,
    'fs': lexers.FSharpLexer, 'fsi': lexers.FSharpLexer, 'fsx': lexers.FSharpLexer,
    'dts': lexers.DevicetreeLexer, 'dtsi': lexers.DevicetreeLexer,
    'yaml': lexers.YamlLexer, 'yml': lexers.YamlLexer,
    'd': lexers.DLexer, 'di': lexers.DLexer,
    'reg': lexers.RegeditLexer,
    'ini': lexers.IniLexer, 'cfg': lexers.IniLexer,
    'ijs': lexers.JLexer,
    'ls': lexers.LiveScriptLexer,
    'nix': lexers.NixLexer,
    'lsp': lexers.NewLispLexer, 'nl': lexers.NewLispLexer, 'kif': lexers.NewLispLexer,
    'cl': lexers.CommonLispLexer, 'lisp': lexers.CommonLispLexer,
    'ps': lexers.PostScriptLexer, 'eps': lexers.PostScriptLexer,
    'tcl': lexers.TclLexer, 'rvt': lexers.TclLexer,
    'jl': lexers.JuliaLexer,
    'adb': lexers.AdaLexer, 'ads': lexers.AdaLexer, 'ada': lexers.AdaLexer,
    'sol': lexers.SolidityLexer,
    'groovy': lexers.GroovyLexer, 'gradle': lexers.GroovyLexer,
    'sci': lexers.ScilabLexer, 'sce': lexers.ScilabLexer, 'tst': lexers.ScilabLexer,
    'zig': lexers.ZigLexer,
    'vbs': lexers.VBScriptLexer, 'VBS': lexers.VBScriptLexer,
    'ex': lexers.ElixirLexer, 'eex': lexers.ElixirLexer, 'exs': lexers.ElixirLexer, 'leex': lexers.ElixirLexer,
    'dart': lexers.DartLexer,
    'scala': lexers.ScalaLexer,
    'ahk': lexers.AutohotkeyLexer, 'ahkl': lexers.AutohotkeyLexer
}

W3_LANGUAGES = {
    'py': 'python/default.asp', 'py3': 'python/default.asp', 'pyw': 'python/default.asp', 'pyi': 'python/default.asp',
    'html': 'html/default.asp', 'htm': 'html/default.asp', 'xhtml': 'html/default.asp',
    'css': 'css/default.asp',
    'java': 'java/default.asp',
    'js': 'js/default.asp', 'jsm': 'js/default.asp', 'mjs': 'js/default.asp', 'cjs': 'js/default.asp',
    'sql': 'sql/default.asp', 'ddl': 'sql/default.asp', 'dml': 'sql/default.asp',
    'php': 'php/default.asp ',
    'cpp': 'cpp/default.asp', 'hpp': 'cpp/default.asp', 'c++': 'cpp/default.asp', 'h++': 'cpp/default.asp',
    'c': 'c/index.php', 'h': 'c/index.php', 'idc': 'c/index.php',
    'cs': 'cs/index.php', 'csx': 'cs/index.php',
    'xml': 'xml/default.asp',
    'ts': 'typescript/index.php',
    'go': 'go/index.php',
    'kt': 'kotlin/index.php', 'kts': 'kotlin/index.php'
}

FILE_TYPES = [("All Files", "*.*"), ("Text Files", "*.txt"), ("Python Files", ["*.py", "*.py3", "*.pyw", "*.pyi"]),
              ("C Files", ["*.c", "*.h", "*.idc"]), ("Lua Files", ["*.lua", "*.luau", "*.wlua"]),
              ("XML Files", "*.xml"), ("C++ Files", ["*.cpp", "*.hpp", "*.c++", "*.h++"]),
              ("HTML Files", ["*.html", "*.htm", "*.xhtml"]), ("C# Files", ["*.cs", "*.csx"]),
              ("JSON Files", ["*.json", "*.jsonl", "*.ndjson", "*.jsonld"]), ("Power Shell Files", ["*.ps1", "*.psm1"]),
              ("Ruby Files", ["*.rb", "*.rbi", "*.rbw", "*.rake"]), ("ini and cfg Files", ["*.ini", "*.cfg"]),
              ("Rust Files", "*.rs"), ("Brainfuck Files", ["*.b", "*.bf"]), ('SQL Files', ["*.sql", "*.ddl", "*.dml"]),
              ("Java Files", "*.java"), ("JavaScript Files", ["*.js", "*.jsm", "*.mjs", "*.cjs"]),
              ("CSS Files", "*.css"), ("Perl Files", ["*.pl", "*.pc"]), ("Delphi Files", ["*.pas", "*.dpr"]),
              ("Coffee Script Files", "*.coffee"), ("Crystal Files", "*.cr"), ("Arduino Files", "*.ino"),
              ("Apple Script Files", "*.applescript"), ("Swift Files", "*.swift"), ("PHP Files", "*.php"),
              ("Matlab Files", ["*.m", "*.matlab"]), ("Cython Files", ["*.pyx", "*.pxd", "*.pxi"]),
              ("Gcode Files", "*.gcode"), ("Cypher Files", ["*.cyp", "*.cypher"]), ("Go Files", "*.go"),
              ("Mojo Files", ["*.mojo", "*.🔥"]), ("Flo Script Files", "*.flo"), ("CUDA Files", ["*.cu", "*.cuh"]),
              ("Action Script 3 Files", "*.as"), ("Clojure Script Files", "*.cljs"), ("Moon Script Files", "*.moon"),
              ("Bash Files", ["*.bash", "*.bashrc", "*.sh", "*.ksh", "*.sh-session", "*.shell-session"]),
              ("Kotlin Files", ["*.kt", "*.kts"]), ("Batch Files", ["*.bat", "*.cmd"]), ("Nix Files", "*.nix"),
              ("Live Script Files", "*.ls"), ("Reg Edit Files", "*.reg"), ("D Files", ["*.d", "*.di"]),
              ("Dylan Files", ["*.dylan", "*.dyl", "*.dylan-console"]), ('Mini Script Files', "*.ms"),
              ("Yaml Files", ["*.yaml", "*.yml"]), ("J Files", "*.ijs"), ("Device Tree Files", ["*.dts", "*.dtsi"]),
              ("F# Files", ["*.fs", "*.fsi", "*.fsx"]), ("Lisp Files", ["*.lsp", "*.lisp", "*.nl", "*.kif", "*.cl"]),
              ("Post Script Files", ["*.ps", "*.eps"]), ("Tcl Files", ["*.tcl", "*.rvt"]),
              ("Julia Files", "*.jl"), ("Ada Files", ["*.ada", "*.adb", "*.ads"]), ("Scala Files", "*.scala"),
              ("Solidity Files", "*.sol"), ("Zig Files", "*.zig"), ("Dart Files", "*.dart"),
              ("Groovy Files", ["*.groovy", "*.gradle"]), ("Scilab Files", ["*.sci", "*.sce", "*.tst"]),
              ("VBS Files", ["*.vbs", "*.VBS"]), ("Elixir Files", ["*.ex", "*.eex", "*.exs", "*.leex"]),
              ("AutoHotKey Files", ["*.ahk", "*.ahkl"])
]

THEMES = {
    0: "Solarized-Light",
    1: "Xcode",
    2: "Monokai",
    3: "Github-Dark",
    4: "RRT",
    5: "Lightbulb",
    6: "Default",
    7: "Gruvbox-Light",
    8: "Gruvbox-Dark",
    9: "Zenburn",
    10: "One-Dark",
    11: "Nord-Darker",
    12: "Paraiso-Dark",
    13: "Stata-Dark",
    14: "Solarized-Dark",
    15: "Fruity",
    16: "Inkpot",
    17: "StarOffice",
    18: "BW",
    19: "SAS",
    20: "Arduino",
    21: "Borland",
    22: "Algol",
    23: "Colorful",
    24: "Rainbow_Dash",
    25: "Emacs",
    26: "Nord",
    27: "Dracula",
    28: "Coffee",
    29: "Trac",
    30: "VS"
}

MAIN_THEMES = {
    0: "Yellow",
    1: "Rose",
    2: "Blue",
    3: "Dark-Blue",
    4: "Green",
    5: "Pink",
    6: "Violet",
    7: "Carrot",
    8: "Coffee",
    9: "Sky",
    10: "Red",
    11: "Marsh",
    12: "Metal"
}

DEFAULT_SETTINGS = {
    "theme": "Dark",
    "codebox_theme": "Solarized-Light",
    "main_theme": "Yellow",
    "font_family": "Arial",
    "font_size": 12,
    "keybinds": "Enabled",
    "auto_load": "Enabled",
    "auto_save": "Enabled",
    "auto_save_file": "Enabled",
    "auto_save_file_time": 3,
    "indent_space": 4
}
